/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterEmployerRouteImport } from './routes/register.employer'
import { Route as RegisterEmployeeRouteImport } from './routes/register.employee'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterEmployerRoute = RegisterEmployerRouteImport.update({
  id: '/register/employer',
  path: '/register/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterEmployeeRoute = RegisterEmployeeRouteImport.update({
  id: '/register/employee',
  path: '/register/employee',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/services': typeof ServicesRoute
  '/register/employee': typeof RegisterEmployeeRoute
  '/register/employer': typeof RegisterEmployerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/services': typeof ServicesRoute
  '/register/employee': typeof RegisterEmployeeRoute
  '/register/employer': typeof RegisterEmployerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/services': typeof ServicesRoute
  '/register/employee': typeof RegisterEmployeeRoute
  '/register/employer': typeof RegisterEmployerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/services'
    | '/register/employee'
    | '/register/employer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/services' | '/register/employee' | '/register/employer'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/services'
    | '/register/employee'
    | '/register/employer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ServicesRoute: typeof ServicesRoute
  RegisterEmployeeRoute: typeof RegisterEmployeeRoute
  RegisterEmployerRoute: typeof RegisterEmployerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/employer': {
      id: '/register/employer'
      path: '/register/employer'
      fullPath: '/register/employer'
      preLoaderRoute: typeof RegisterEmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/employee': {
      id: '/register/employee'
      path: '/register/employee'
      fullPath: '/register/employee'
      preLoaderRoute: typeof RegisterEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ServicesRoute: ServicesRoute,
  RegisterEmployeeRoute: RegisterEmployeeRoute,
  RegisterEmployerRoute: RegisterEmployerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
